Fix defaults options
nuxt-community/universal-storage-module pull request #168
Opened 2021-01-25 09:47 UTC by SvMak

2021-01-25 10:14 UTC, Atinux approved these changes

2021-02-04 10:30 UTC, farzadso approved these changes
LGTM!

2021-03-11 09:39 UTC, rxsto commented
How are things looking here? 👀

2021-04-08 08:06 UTC, farzadso commented
@rxsto The tests are failing. Please check it.

2021-04-10 14:15 UTC, farzadso requested changes
This will fix the tests. I tested it thoroughly and it seems like there were no issues.

2021-04-10 14:15 UTC, farzadso commented on src/module.ts
> +  const options: Options = defu(moduleOptions, this.options.storage, defaults)
```suggestion
  const options: DeepPartial<Options> = defu(moduleOptions, { ...this.options.storage }, defaults)
```

2021-04-10 15:05 UTC, SvMak commented on src/module.ts
> +  const options: Options = defu(moduleOptions, this.options.storage, defaults)
Thanks a lot

2021-04-10 15:23 UTC, merged